backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Social Image", name: "og_image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "writeups"
    label: "Writeups"
    folder: "_writeups"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Event", name: "event", widget: "string", required: false }
      - { label: "Team", name: "team", widget: "string", required: false }
      - { label: "PDF File", name: "pdf", widget: "file", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
          - { label: "Body", name: "body", widget: "markdown" }
